// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjC-y_mnXAtCVGb3lFjIzGQz_88nfdO5I',
    appId: '1:1070938226813:web:88b94fd9f1768139fa7114',
    messagingSenderId: '1070938226813',
    projectId: 'auth-test-65630',
    authDomain: 'auth-test-65630.firebaseapp.com',
    storageBucket: 'auth-test-65630.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCee9E7UxossjVJRD9yYVUqcu8Xosxfco0',
    appId: '1:1070938226813:android:c82b47e8d1880720fa7114',
    messagingSenderId: '1070938226813',
    projectId: 'auth-test-65630',
    storageBucket: 'auth-test-65630.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_7b6_DttfzgnWIvv6dY_3ALalu8PWgmk',
    appId: '1:1070938226813:ios:af5619ef1392304bfa7114',
    messagingSenderId: '1070938226813',
    projectId: 'auth-test-65630',
    storageBucket: 'auth-test-65630.appspot.com',
    iosBundleId: 'com.example.ocrTake2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_7b6_DttfzgnWIvv6dY_3ALalu8PWgmk',
    appId: '1:1070938226813:ios:af5619ef1392304bfa7114',
    messagingSenderId: '1070938226813',
    projectId: 'auth-test-65630',
    storageBucket: 'auth-test-65630.appspot.com',
    iosBundleId: 'com.example.ocrTake2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjC-y_mnXAtCVGb3lFjIzGQz_88nfdO5I',
    appId: '1:1070938226813:web:c356f120da36aed0fa7114',
    messagingSenderId: '1070938226813',
    projectId: 'auth-test-65630',
    authDomain: 'auth-test-65630.firebaseapp.com',
    storageBucket: 'auth-test-65630.appspot.com',
  );
}
